#!/usr/bin/env bash

case "$1" in
    docker)
        echo "### building rawrepo-content-service docker ###"
        docker build . -t docker-metascrum.artifacts.dbccloud.dk/rawrepo-content-service:devel || exit 1
        if [[ ! -z "$BUILD_NUMBER" ]]; then
            docker tag docker-metascrum.artifacts.dbccloud.dk/rawrepo-content-service:devel docker-metascrum.artifacts.dbccloud.dk/rawrepo-content-service:${BRANCH_NAME}-${BUILD_NUMBER}
        fi
        ;;

    *)
        echo "### building rawrepo-content-service project ###"
        echo "### Look for build artifacts in target/ ###"

        mvn package -Dmaven.test.skip=true || exit 1
        ;;
esac
