#!/usr/bin/env bash

./stop || true
./build docker || exit 1

echo "### Starting rawrepo-content-service docker ###"

content_service_port=${RAWREPO_CONTENT_SERVICE_PORT:-8080}
docker run --rm --name rawrepo-content-service -d -p ${content_service_port}:8080 \
    -e INSTANCE_NAME=${USER}_dev \
    -e VIPCORE_CACHE_AGE="0" \
    -e VIPCORE_ENDPOINT="http://vipcore.iscrum-vip-extern-test.svc.cloud.dbc.dk" \
    -e RAWREPO_DB_URL=${RAWREPO_DB_URL} \
    -e JAVA_MAX_HEAP_SIZE=2G \
    docker-io.dbc.dk/rawrepo-content-service:devel
attempts=0
max_attempts=60
until $(curl --output /dev/null --silent --head --fail http://localhost:${content_service_port}/RawRepoContentService); do
    if [ ${attempts} -eq ${max_attempts} ]; then
        break
    fi

    printf '.'
    attempts=$(($attempts+1))
    sleep 0.5
done

echo ""
echo "### Status for rawrepo-content-service service ###"
curl -vs http://localhost:${content_service_port}/RawRepoContentService
echo ""
