worker:
  queueServer: ${QUEUE_SERVER}
  pollInterval: ${POLL_INTERVAL:-5}
  dbToMqThreads: ${DB_TO_MQ_THREADS:-1}
  mqToDbThreads: ${MQ_TO_DB_THREADS:-1}
  dbToMqQueues: "${DB_TO_MQ_QUEUES:-}"
  mqToDbQueues: "${MQ_TO_DB_QUEUES:-}"

database:
  driverClass: org.postgresql.Driver
  user: ${RAWREPO_URL_USER}
  password: ${RAWREPO_URL_PASS}
  url: jdbc:postgresql://${RAWREPO_URL_BASE}
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  initialSize: ${POSTGRES_POOL_MIN:-1}
  minSize: ${POSTGRES_POOL_MIN:-1}
  maxSize: ${POSTGRES_POOL_MAX:-8}
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: ${HTTP_PORT:-8080}
  adminConnectors:
    - type: http
      port: ${HTTP_ADMIN_PORT:-8081}
