#!/bin/bash -e

cd "${0%/*}"

name=rawrepo
tmp=../target/validate-upgrade
mkdir -p $tmp
rm -f $tmp/log

if [ $# = 0 ]; then 
    version=`ls -f $name-*-upgrade.sql | sort -n | tail -n 1`
    version=${version/$name-/}
    version=${version/-*/}

    if ! cmp -s $name-$version.sql $name.sql; then
	echo "updating latest stable ($version) from current"
	cp $name.sql $name-$version.sql
    fi
else
    version=$(($1))
fi


V="`ls -f /usr/lib/postgresql/ | sort -n | tail -n 1`"
export PGHOST=/tmp/$$

trap '/usr/lib/postgresql/$V/bin/pg_ctl stop -D $PGHOST/data >>$tmp/log 2>&1 ; rm -rf $PGHOST' EXIT

if [ ! -e $tmp/$name-$version.schema ] ||
   [ $tmp/$name-$version.schema -ot $name-$version.sql ]; then
    echo "building $name-$version.schema"
    (
	rm -rf $PGHOST
	/usr/lib/postgresql/$V/bin/pg_ctl initdb -D $PGHOST/data
	/usr/lib/postgresql/$V/bin/pg_ctl start -w -D $PGHOST/data -l $PGHOST/log -o "-h '' -k $PGHOST" 1>&2
	cat - $name-$version.sql <<-EOT | psql postgres
\set ON_ERROR_STOP
CREATE DATABASE data;
CREATE ROLE duser WITH PASSWORD 'dpass' LOGIN SUPERUSER;
GRANT ALL PRIVILEGES ON DATABASE data TO duser;
\\connect data
EOT
	pg_dump -s -f $tmp/$name-$version.schema data
	/usr/lib/postgresql/$V/bin/pg_ctl stop -D $PGHOST/data
	rm -rf $PGHOST
    ) >>$tmp/log 2>&1
    if grep -q ^ERROR: $tmp/log; then
	echo "SQL ERROR see $tmp/log"
	rm -f $tmp/$name-$version.schema
	exit 1
    fi
fi

if [ ! -e $tmp/$name-$version-upgrade.schema ] ||
   [ $tmp/$name-$version-upgrade.schema -ot $name-$(($version - 1)).sql ] ||
   [ $tmp/$name-$version-upgrade.schema -ot $name-$version-upgrade.sql ]; then
    echo "building $name-$version-upgrade.schema"
    (
	rm -rf $PGHOST
	/usr/lib/postgresql/$V/bin/pg_ctl initdb -D $PGHOST/data
	/usr/lib/postgresql/$V/bin/pg_ctl start -w -D $PGHOST/data -l $PGHOST/log -o "-h '' -k $PGHOST" 1>&2
	cat - $name-$(($version - 1)).sql $name-$version-upgrade.sql <<-EOT | psql postgres
\set ON_ERROR_STOP
CREATE DATABASE data;
CREATE ROLE duser WITH PASSWORD 'dpass' LOGIN SUPERUSER;
GRANT ALL PRIVILEGES ON DATABASE data TO duser;
\\connect data
EOT
	pg_dump -s -f $tmp/$name-$version-upgrade.schema data
	/usr/lib/postgresql/$V/bin/pg_ctl stop -D $PGHOST/data
	rm -rf $PGHOST
    ) >>$tmp/log 2>&1
    if grep -q ^ERROR: $tmp/log; then
	echo "SQL ERROR see $tmp/log"
	rm -f $tmp/$name-$version-upgrade.schema
	exit 1
    fi
fi

java -jar tools/apgdiff-2.4.jar --ignore-start-with $tmp/$name-$version-upgrade.schema $tmp/$name-$version.schema

